# Generated by Django 6.0.5 on 2026-05-29 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('whatsapp', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('joining_date', models.DateField()),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee_status', models.CharField(default='Pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
