# Generated by Django 6.0.5 on 2026-05-30 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_student_email_remove_student_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='father_name',
        ),
        migrations.AddField(
            model_name='student',
            name='aadhaar_card',
            field=models.CharField(default=0, max_length=12),
            preserve_default=False,
        ),
    ]
