# Generated by Django 6.0.5 on 2026-05-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_student_father_name_student_aadhaar_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='father_name',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='whatsapp',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
