# Generated by Django 6.0.5 on 2026-05-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_father_name_student_whatsapp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='mobile',
        ),
        migrations.AlterField(
            model_name='student',
            name='whatsapp',
            field=models.CharField(max_length=10),
        ),
    ]
