# Generated by Django 6.0.5 on 2026-06-02 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library_name', models.CharField(max_length=200)),
                ('library_address', models.TextField()),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('cafe_name', models.CharField(max_length=200)),
                ('gst_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('service_charge', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('email_notifications', models.BooleanField(default=True)),
                ('whatsapp_notifications', models.BooleanField(default=True)),
                ('dark_mode', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=17),
        ),
    ]
