# Generated by Django 6.0.5 on 2026-06-04 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_settings_alter_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='receipt_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
