# Generated by Django 6.0.5 on 2026-06-04 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_settings_receipt_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='receipt_url',
        ),
    ]
