# Generated by Django 6.0.5 on 2026-06-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_remove_settings_receipt_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='receipt_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
