# Generated by Django 6.0.5 on 2026-06-09 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_student_receipt_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='receipt_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
