# Generated by Django 6.0.5 on 2026-06-09 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_payment_receipt_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='receipt_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
